{% set python_min = "3.10" %}
{% set name = "micropip" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/micropip-{{ version }}.tar.gz
  sha256: 9639ba9927d637b608ae18519b430009ead6a336f66b10095c7fdc64d38dd95e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    # From https://github.com/pyodide/pyodide/blob/main/packages/micropip/meta.yaml#L16
    - packaging
    - pyparsing
    - pyodide-py

test:
  imports:
    - micropip
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/micropip/
  summary: A lightweight Python package installer for the web
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtpio
    - yuvipanda
