{% set name = "micropip" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/micropip-{{ version }}.tar.gz
  sha256: 9af8533b59e3b46e51533cbcf1968998084c449181cf0fd443a9026f25ecd04a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    # From https://github.com/pyodide/pyodide/blob/main/packages/micropip/meta.yaml#L16
    - packaging
    - pyparsing
    - pyodide-py

test:
  imports:
    - micropip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/micropip/
  summary: A lightweight Python package installer for the web
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yuvipanda
